### PR TITLE
Fix wrong processor mode in first time exception return

### LINKED ISSUE #23: Functions declared with the naked attribute also require basic asm
https://github.com/jserv/mini-arm-os/blob/4437a6596e694aa6db83680923323a3bc53d8a37/07-Threads/threads.c#L29

According to gcc onlinedocs:https://gcc.gnu.org/onlinedocs/gcc/ARM-Function-Attributes.html

### LINKED ISSUE #27: Wrong processor mode in first time exception return
According to https://www.ptt.cc/bbs/ASM/M.1534260340.A.DC5.html

3d4ea334a96f20b78dace4da7ab145a7d906283c is buggy due to reset is in `privilege level` and `thread mode`.

But the commit assume `reset_handler` is in `Handler mode` and makes undefined behavior when first calling `activate` except `06-Preemptive`.

By some experiment, I acknowledge that it can still work well in QEMU but fail in real HW (STMF429), and that misled me during checking 3d4ea334a96f20b78dace4da7ab145a7d906283c.

I've solving it in my local by hacking `activate` or `thread_start`.
After cleanup the code, I will make a PR to solve it.

### PR DESCRIPTION
**Pull request by lecopzer**
Close #27 , fix 04, 07 and 08 which run first thread in wrong mode. See the comments in each commit in detail. 
Close #23 , add `naked` attribute before `thread_start`

### CODE REVIEW

File: 04-Multitasking/os.c [hunk 1]
```diff
@@ -63,6 +63,16 @@ unsigned int *create_task(unsigned int *stack, void (*start)(void))
 	return stack;
 }
 
+/* Reset mode is at thread and priviledge mode, so that
```
Comment (jserv) [inline 04-Multitasking/os.c]: Fix the grammar.

File: 07-Threads/threads.c [hunk 2]
```diff
@@ -49,23 +49,33 @@ void systick_handler()
...
-                    "msr psp, r0\n"
-                    "bx lr\n");
+	asm volatile("msr psp, r0\n"
+	             "mov r0, #3\n"
+	             "msr control, r0\n"
+	             "isb\n");
+	/* Restore the new task's context */
+	asm volatile("pop {r4-r11, lr}\n"
+	             "pop {r0}\n");
+	/* Okay, we are ready to run test1, get test1 address from
```
Comment (jserv) [inline 07-Threads/threads.c]: Explain how the scenario of task switching has been functioned.

**Comment by lecopzer** [comment]
Please review it again, thanks.

File: 04-Multitasking/asm.h [hunk 3]
```diff
@@ -2,6 +2,7 @@
 #define __ASM_H_
 
 unsigned int *activate(unsigned int *stack);
+void init_activate_env(unsigned int *stack);
```
Comment (jserv) [inline 04-Multitasking/asm.h]: `init_activate_env` might be a misleading name since it is specific to two operations: init and activate. However, its functionality is to construct task-switching environment.

File: 04-Multitasking/os.c [hunk 4]
```diff
@@ -63,6 +63,16 @@ unsigned int *create_task(unsigned int *stack, void (*start)(void))
 	return stack;
 }
 
+/* After reset, processor is at thread and priviledge mode.
```
Comment (jserv) [inline 04-Multitasking/os.c]: Typo. should be "privileged" mode.

File: 04-Multitasking/os.c [hunk 5]
```diff
@@ -63,6 +63,16 @@ unsigned int *create_task(unsigned int *stack, void (*start)(void))
...
+ * Switch to handler mode to make sure exception return
+ * works well.
```
Comment (jserv) [inline 04-Multitasking/os.c]: Change to "ensure an appropriate exception return".

File: 07-Threads/threads.c [hunk 6]
```diff
@@ -49,23 +49,37 @@ void systick_handler()
...
-void thread_start()
+void __attribute__((naked)) thread_start()
 {
 	lastTask = 0;
 
-	/* Save kernel context */
-	asm volatile("mrs ip, psr\n"
-	             "push {r4-r11, ip, lr}\n");
-
+	/* Reset APSR before context switch */
```
Comment (jserv) [inline 07-Threads/threads.c]: You shall explain the reason.

Comment (lecopzer) [reply 07-Threads/threads.c]: Actually, I am hesitate to reset this. This in fact has no influence in switching first task unless the task use condition flag instruction right away switching to it.

It's just like there is a `int *p`, and I want to initialize it to `int *p = NULL`.

This might also complicate the flow, even though we had assigned stack[16] as reset value of `psr` and should also keep consistent here with `pendsv_handler`.

What do you think about this?

File: 04-Multitasking/asm.h (hunk 3 above)
Comment (lecopzer) [reply 04-Multitasking/asm.h]: But we use activate to switch task; I think it means init the environment that activate can function.
(It's copied from 06-Preemptive, I'm not pretty sure about the naming issue.)
Or is any suggestion for the function name?

File: 07-Threads/threads.c [hunk 7]
```diff
@@ -49,23 +49,37 @@ void systick_handler()
...
-	/* Load user task's context and jump to the task */
-	asm volatile("ldmia r0!, {r4-r11, lr}\n"
-                    "msr psp, r0\n"
-                    "bx lr\n");
+	asm volatile("msr psp, r0\n"
+	             "mov r0, #3\n"
+	             "msr control, r0\n"
+	             "isb\n");
+	/* This is how we simulate stack handling that pendsv_handler
+	 * does. Thread_create sets 17 entries in stack, and the 9
```
Comment (jserv) [inline 07-Threads/threads.c]: Can you illustrate with some text-based diagram(s)?

File: 08-CMSIS/core/src/threads.c [hunk 8]
```diff
@@ -45,20 +45,38 @@ void __attribute__((naked)) pendsv_handler()
...
+	/* Okay, we are ready to run test1, get test1 address from
+	 * stack[15]. We just pop 10 register so #24 comes from
+	 * (15 - 9) * sizeof(entry of sp) = 6 * 4.
+	 */
+	asm volatile("ldr pc, [sp, #24]\n");
 
-	/* Save kernel context */
-	asm volatile("mrs ip, psr\n"
-	             "push {r4-r11, ip, lr}\n");
+	/* Never get here */
```
Comment (jserv) [inline 08-CMSIS/core/src/threads.c]: Shall be "Never reach here."

File: 08-CMSIS/core/src/threads.c [hunk 9]
```diff
@@ -45,20 +45,38 @@ void __attribute__((naked)) pendsv_handler()
...
+	__ISB();
+
+	/* This is how we simulate stack handling that pendsv_handler
+	 * does. Thread_create sets 17 entries in stack, and the 9
+	 * entries we pop here will be pushed back in pendsv_handler
+	 * in the same order.
+	 */
+	asm volatile("pop {r4-r11, lr}\n"
+	             "ldr r0, [sp]\n");
+	/* Okay, we are ready to run test1, get test1 address from
```
Comment (jserv) [inline 08-CMSIS/core/src/threads.c]: Avoid mentioing `test1` since it is not really specific to the whole design. Instead, use general terms.

File: 07-Threads/threads.c (hunk 7 above)
Comment (lecopzer) [reply 07-Threads/threads.c]: Yes, as this diagram is accepted, I can copy to 08-CMSIS or move to a document (although there is no such file for document now)

Comment (lecopzer) [reply 07-Threads/threads.c]: If the diagram is okay, I'll copy to 08-CMSIS?

Comment (jserv) [reply 07-Threads/threads.c]: Please go ahead.

File: 04-Multitasking/os.c [hunk 10]
```diff
@@ -63,6 +63,15 @@ unsigned int *create_task(unsigned int *stack, void (*start)(void))
 	return stack;
 }
 
+/* After reset, processor is at thread and privileged mode.
+ * Switch to handler mode to ensure an appropriate exception return.
+ */
+void task_init(void)
+{
+	unsigned int null_stacks[32];
```
Comment (jserv) [inline 04-Multitasking/os.c]: `null_stacks` is not an effective name. How about empty?

Comment (lecopzer) [reply 04-Multitasking/os.c]: Ok, this may apply to 06-Preemptive too.

**Comment by lecopzer** [comment]
Excuse me, are there any comments?

File: 07-Threads/threads.c [hunk 11]
```diff
@@ -49,23 +49,66 @@ void systick_handler()
...
+	 *         -------                              -------
+	 *        |   7   |                            |  r11  |
+	 *         -------                              -------
+	 *        |  ...  |                            |  ...  |
+	 *         -------                              -------
+	 *        |   0   |                            |   r4  |
+	 * psp ->  -------                              -------
+	 *
+	 * Instead of "pop {r0}", use "ldr r0, [sp]" to ensure consistent
+	 * with the way how PendSV saves _old_ context.
```
Comment (jserv) [inline 07-Threads/threads.c]: You can add some Arm references as Piko/RT did.

Comment (lecopzer) [reply 07-Threads/threads.c]: Do you mean something like this below?

https://github.com/PikoRT/pikoRT/blob/master/arch/v7m-entry.S#L141
```
/* [a] https://lists.nongnu.org/archive/html/qemu-devel/2014-12/msg01575.html
 *     ADP_Stopped_ApplicationExit is used for exit(0), anything else is
 *     implemented as exit(1). */
```

Comment (jserv) [reply 07-Threads/threads.c]: Exactly. It would be informative if these links to Arm specific resources are landed.

Comment (lecopzer) [reply 07-Threads/threads.c]: Got it.

But I have an question:
Is web link appropriate to appear in comments?

It seems we have to maintain links in comments that might be not persistent in both its web address and content.
Maybe provide the document name such as `ARM® Architecture Reference Manual
ARMv8, for ARMv8-A architecture profile (ARM DDI 0487C.a)` and the chapter is better, so that people who is interesting in the detail would find the document itself.

Comment (jserv) [reply 07-Threads/threads.c]: I agree with the way to mention chapters and sections accordingly.

**Comment by lecopzer** [comment]
Update reference in both 07 and 08
https://github.com/jserv/mini-arm-os/blob/5dd4e08e58d988ff5c4f95639553862bc2653ae6/07-Threads/threads.c#L169-L178

File: 04-Multitasking/os.c [hunk 12]
```diff
@@ -63,6 +63,15 @@ unsigned int *create_task(unsigned int *stack, void (*start)(void))
 	return stack;
 }
 
+/* After reset, processor is at thread and privileged mode.
+ * Switch to handler mode to ensure an appropriate exception return.
+ */
+void task_init(void)
+{
+	unsigned int empty[32];
+	task_init_env(&empty[32]);
```
Comment (jserv) [inline 04-Multitasking/os.c]: The use of `&empty[32]` is a bit puzzling. How about `empty + 32`?

File: 07-Threads/threads.c [hunk 13]
```diff
@@ -49,23 +49,66 @@ void systick_handler()
 	*SCB_ICSR |= SCB_ICSR_PENDSVSET;
 }
 
-void thread_start()
+void __attribute__((naked)) thread_start()
```
Comment (jserv) [inline 07-Threads/threads.c]: You shall explain why naked attribute is necessary here.

**Comment by lecopzer** [comment]
Update  `empty + 32` and comments for naked attribute
